version: '3'

networks:
  backend:
    driver: bridge

services:
  db:
    build: ./dockerfiles/db
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
    networks:
      - backend
  app:
    build: 
      dockerfile: ./dockerfiles/app/Dockerfile
      context: .
    command: "bin/mix_release_example start"
    environment:
      - DB_USER=default
      - DB_PASSWORD=secret
      - DB_NAME=default
      - DB_PORT=5432
      - DB_HOST=db
      - SECRET_KEY_BASE=qEb5cvzNQYgNogxW8pxIexlp2cff9i5E2dWqTyHKsCYxSsEDwJz6GCzcc2l2Oy/0
    ports:
      - "4000:4000"
    networks:
      - backend